-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 17:53:51 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `fisrtname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `school` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `console` VARCHAR(45) NULL,
  `pc` VARCHAR(45) NULL,
  `videogame` VARCHAR(45) NULL,
  `picture` LONGBLOB NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL,
  `message` TEXT NULL,
  `picture` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  PRIMARY KEY (`idpost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`follow` (
  `idfollow` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL,
  `idFollowed` INT NULL,
  `startDate` DATETIME NULL,
  PRIMARY KEY (`idfollow`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`like` (
  `idlike` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL,
  `idPost` INT NULL,
  `likeType` TINYINT(1) NULL,
  PRIMARY KEY (`idlike`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `idcomments` INT NOT NULL AUTO_INCREMENT,
  `idPost` INT NULL,
  `idUser` INT NULL,
  `message` TEXT NULL,
  PRIMARY KEY (`idcomments`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
